//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class admission
    {
        public int SerialNo { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email_ID { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Notes { get; set; }
        public string WhatProfession { get; set; }
        public string CollegeName { get; set; }
        public string StudentMajor { get; set; }
        public string CompanyName { get; set; }
        public string EmployeeDesignation { get; set; }
        public string CourseTaken { get; set; }
        public string CourseFee { get; set; }
        public Nullable<System.DateTime> CourseEnd { get; set; }
        public string CertificateStatus { get; set; }
        public string BreakOfStudy { get; set; }
    }
}
