//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admission> admissions { get; set; }
        public DbSet<enquiry> enquiries { get; set; }
        public DbSet<internship> internships { get; set; }
        public DbSet<ipt> ipts { get; set; }
        public DbSet<meetup> meetups { get; set; }
        public DbSet<userdetail> userdetails { get; set; }
    }
}
