//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        public int SerialNo { get; set; }
        public Nullable<System.DateTime> DateOfEnquiry { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email_ID { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Mode { get; set; }
        public string Notes { get; set; }
        public string Interested { get; set; }
        public string TimePreferred { get; set; }
        public string Referrals { get; set; }
        public string Profession { get; set; }
        public string CollegeName { get; set; }
        public string StudentMajor { get; set; }
        public string CompanyName { get; set; }
        public string EmpDesignation { get; set; }
        public string WhoTheyMet { get; set; }
        public string Discussion { get; set; }
        public string EnrollmentStatus { get; set; }
        public string FollowUp { get; set; }
    }
}
